### ISSUE TITLE
Specify optional modules in RELEASE_PRODS.local

### ISSUE THREAD

**Issue by kmpeters** [areaDetector/areaDetector#11]
This is related to ADCore issue #108.
The optional-but-useful modules that are conditionally included in ADCore/ADApp/commonDriverMakefile should be clearly identifiable in RELEASE_PRODS.local

**Comment by MarkRivers** [comment]
This issue is fixed.  3rd party modules are optionally used if WITH_XXX=YES.  EPICS modules are optionally used if they are defined in RELEASE_PRODS.local.
