### ISSUE TITLE
Addition of driver for the Dectris Eiger detector

### ISSUE THREAD

**Issue by brunoseivam** [areaDetector/areaDetector#15]
Hi everyone,

Is there interest in having the driver for the Eiger detector inside areaDetector?

Currently it is [here](https://github.com/brunoseivam/ADEiger/).

Bruno

**Comment by brunoseivam** [comment]
Hi @MarkRivers,

Do you think we can move ahead with this? I can transfer the ownership of my repo and then open a PR.

(att @GDYendell)

**Comment by MarkRivers** [comment]
Yes, that sounds great.  Thanks,

**Comment by brunoseivam** [comment]
Hmm, I get this

    You don’t have the permission to create repositories on areaDetector

Could you grant me temporary permissions?

**Comment by MarkRivers** [comment]
I just added you to the team that used to be called Owners but that Github made me rename, so I called it Core.  That should let you create a repository.  If not let me know.
