### ISSUE TITLE
Changes to allow building when using an EPICS Debian distribution

### ISSUE THREAD

**Issue by MarkRivers** [areaDetector/areaDetector#26]
The areaDetector/configure/RELEASE* files have problems when building with EPICS_BASE and some modules from the Debian EPICS package.  This is a problem at NSLS-II, for example.

**Comment by MarkRivers** [comment]
I have changed the RELEASE* files so that it should now be possible to use EPICS_BASE and some modules from the Debian package, while using different versions of areaDetector and other modules.

I have updated RELEASE.md and INSTALL_GUIDE.md to explain the new system.  I don't have a Debian system so I cannot test it. 

Please look at the changes, test if possible, and send me any comments.

**Comment by mdavidsaver** [comment]
To summarize what I see.  The core change is to switch to the *.local convention for RELEASE and CONFIG_SITE with the added wrinkle that some of .local files are mandatory.  Though, so far as I have seen this is only in the top level module/repo.  As this isn't (currently) used by debian package builds, it isn't relevant.

https://github.com/areaDetector/areaDetector/blob/b22b5e1c0365fd672d814b901061fd36b53e1cb6/configure/RELEASE#L5-L8

I haven't looked at all of the individual modules, but I assume that they are all intended to follow the pattern of ADCore.

https://github.com/areaDetector/ADCore/blob/cf1be73ede3d0077254dc395c1d2c21ff979910c/configure/RELEASE#L5-L7

Without having had the time to update the packaging, this seems reasonable.  It will be one less patch to carry around.

@mark0n @dchabot fyi

**Comment by MarkRivers** [comment]
The most importance difference is that RELEASE_PATHS.local was replaced by RELEASE_SUPPORT.local.  RELEASE_PATHS.local used to define EPICS_BASE.  This led to EPICS_BASE being defined before other modules.  If EPICS_BASE was pointing to the Debian package, then the build system would find the other module header and library files in that location, rather than the newer versions that are built from base (e.g. asyn).

Oksana has tested the new version at NSLS-II where she is using a recent asyn and areaDetector, but the Debian packages for calc, busy, etc.  It seems to work fine, so I will close this.
