### ISSUE TITLE
ffmpegServer IOC depends on ADSimDetector but is built before it

### ISSUE THREAD

**Issue by jlmuir** [areaDetector/areaDetector#30]
The `ffmpegServer` plugin IOCs depend on `ADSimDetector`, but `ffmpegServer` is built before `ADSimDetector` in `Makefile`, so the first IOC that is built (i.e., `iocs/example`) will fail to build if `BUILD_IOCS` is `YES`.

Specifically, it will fail to generate `example_expanded.db` because `example_expanded.substitutions` references `$(ADSIMDETECTOR)/db/simDetector.template` which has not been installed yet because `ADSimDetector` has not been built yet.

**Comment by MarkRivers** [comment]
This is a chicken and egg problem.  One might well want to build ADSimDetector (and any other detector) with support for the ffmpegServer plugin.  That means that ffmpegServer (and all plugins) must be built before the detectors are built.

However, ffmpegServer (a plugin) comes with example IOCs that use ADSimDetector.  IMHO this is a bad design, and the iocs directory in ffmpegServer should be removed.  Only detectors should have example iocs/ directories, not optional plugins.
