### ISSUE TITLE
Need GenICam base class driver

### ISSUE THREAD

**Issue by MarkRivers** [areaDetector/areaDetector#36]
Many cameras now use the GenICam standard.  This includes GigE, 10GigE, USB-3, and some CameraLink cameras.  For all of these the list of camera "features" is available from an XML file in the camera.  The features are self-describing (data type, range, availability, etc.) and can be accessed in a generic manner.

The areaDetector aravisGigE driver does a nice job of abstracting the features.  It comes with Python scripts that create database .template files, edm .edl files, and medm .adl files from the XML files.  

There are however, several limitations of the aravisGigE driver:
- It only works on Linux.  Some sites want to use Windows.
- It does not achieve the maximum performance for 10Gbit cameras (and perhaps USB-3 cameras).  The vendor APIs have better performance (e.g. Spinnaker for Point Grey 10Gbit cameras).

I propose the following:

- Write an ADGenICam base class driver.  It will implement the GenICam standard in a manner that is independent of the final driver calls.  This driver would basically be a stripped down version of the aravisGigE driver that removes all calls to the aravis and glib APIs.

- Write 3 new drivers that derive from ADGenICam.  These drivers will make the calls to the lower-level drivers to actually set/get features and to stream the images.
  - aravisGigE.  This will use aravis and glib.  It will run only on Linux.
  - ADSpinnaker.  This will use the FLIR/Point Grey Spinnaker SDK.  It will run on Windows and on Linux (Ubuntu 16 only).
  - ADVimba.  This will use the AVT Vimba SDK.  It will run on Windows and Linux (nearly all modern versions, including ARM).

I'd be interested to hear others' thoughts on this.

**Comment by thomascobb** [comment]
This sounds like a really nice idea, but I'm not sure on the details. I'm assuming that the new GenICam implementation would take a genicam XML string, then parse it and provide a suitable API for the areaDetector driver to create or maintain the correct parameters. I think there is a reference document and implementation for GenICam which is BSD licensed, so that plus the aravisGigE implementation gives a reasonable starting point for this. I still have a number of questions though:

- How would you get the genicam XML string in the first place, do all the vendor libraries expose it?
- How do you handle register gets/sets, do you send it down via feature name and let the vendor libraries genicam implementation translate to register number, or do all vendor APIs allow a set from a register number?
- Would you keep the existing "support a new camera" workflow: grab genicam, python script creates db+adl+edl, driver takes db as the source of features to expose? Or would you somehow create database records on the fly from the genicam read at runtime?

**Comment by thomascobb** [comment]
Another alternative would to try and make aravis work on windows, which in theory should be possible as glib and libxml are both compilable for windows. No idea how much effort that is though. 
That still leaves the performance issues on Linux. Did you try giving aravis cap_net_raw?

https://github.com/AravisProject/aravis#packet-socket-support

**Comment by MarkRivers** [comment]
> How would you get the genicam XML string in the first place, do all the vendor libraries expose it?

> Would you keep the existing "support a new camera" workflow: grab genicam, python script creates db+adl+edl, driver takes db as the source of features to expose? Or would you somehow create database records on the fly from the genicam read at runtime?

My initial plan is to continue to use arvtool to grab the XML string, and Python scripts to generate database and OPI files.  

The GenICam class would have methods to get/set features in a generic way, while derived classes would do the actual I/O using the vendor SDK (aravis, Spinnaker, Vimba).  I just don't want to be reinventing these feature classes from scratch for each SDK.  The GeniCam class may not be what the driver derives from, but rather just what the driver feature class derives from.

> How do you handle register gets/sets, do you send it down via feature name and let the vendor libraries genicam implementation translate to register number, or do all vendor APIs allow a set from a register number?

I was planning to just support feature names, and not explicitly register get/set.  Is there a need for that?  Is it used by aravisGigE driver?

> Did you try giving aravis cap_net_raw?

No, I did not try that yet.  If that is enabled does aravis automatically use it?  What about other SDKs?

**Comment by thomascobb** [comment]
> The GenICam class would have methods to get/set features in a generic way, while derived classes would do the actual I/O using the vendor SDK (aravis, Spinnaker, Vimba). I just don't want to be reinventing these feature classes from scratch for each SDK. The GeniCam class may not be what the driver derives from, but rather just what the driver feature class derives from.

That makes sense. I can see how it would work for `set*Param`, but I'm still a little fuzzy on how the cut down GenICam fits into this. Could you drop the need for it altogether by providing abstract `hasEnumString`, `lookupPixelFormat`, `hasFeature` methods that could be implemented? That would mean that the only thing that needs to parse genicam XML is the Python scripts, then the baseclass driver would get told what features and types to create from `drvUserCreate`, and the derived classes would provide `getFeature` and `setFeature` methods.

>  I was planning to just support feature names, and not explicitly register get/set. Is there a need for that? Is it used by aravisGigE driver?

Aravis supports this, but I don't expose it in the aravisGigE driver. The only reason to use it would be to support the serial port in the AVT cameras to drive a remote lens drive (something we were previously considered but have since dropped). The serial port is only accessible with a register, not via the GenICam.



> > Did you try giving aravis cap_net_raw?

> No, I did not try that yet. If that is enabled does aravis automatically use it? What about other SDKs?

I believe it does, the web page I linked gives more details. It is the IOC executable that needs to be given these capabilities. Not sure what method other SDKs use on Linux. A kernel driver? Or maybe they're just written in a more performant way...

**Comment by MarkRivers** [comment]
> That makes sense. I can see how it would work for set*Param, but I'm still a little fuzzy on how the cut down GenICam fits into this. 

I was not being clear. I don't propose to add any code from GenICam itself.  I propose to make a new class with GenICam in the name that will handle the common tasks that any driver that needs to set/get GenICam features will need.  This includes a feature class that tracks the feature name, associated asynPortDriver parameter index, feature type, enum strings, etc.  There would also be a list of features.  These are things that are being handled with glib structures in aravisGigE but need to be made independent of glib to be used in other drivers.  We should be able to use std:: for these.

Each driver would derive from these classes to add the things that are specific to that SDK.

We might want to push this to an even higher level that is independent of GenICAM.  If you look at ADEiger, ADAndor3, ADPointGrey, etc. they are all defining property structures and property lists in a way that probably could be generalized.

**Comment by thomascobb** [comment]
This sounds like a good approach, there are definitely areas of overlapping code between the drivers you mention.

I'm not sure how high level it would be best to make it, there is definitely a case for pushing it higher than GenICAM, but it might snowball in terms of complexity...

**Comment by MarkRivers** [comment]
I have made some progress on this.  I have created a new ADGenICam repository.  It borrows heavily from the ideas and code in aravisGigE and ADEiger.

It defines 3 base classes:
- GenICamFeature
  - This is a generic class for GenICam features.
  - Inherited classes must implement the following pure virtual functions:
```
    virtual bool isImplemented(void) = 0;
    virtual bool isAvailable(void) = 0;
    virtual bool isReadable(void) = 0;
    virtual bool isWritable(void) = 0;
    virtual int readInteger(void) = 0;
    virtual int readIntegerMin(void) = 0;
    virtual int readIntegerMax(void) = 0;
    virtual int readIncrement(void) = 0;
    virtual void writeInteger(int value) = 0;
    virtual bool readBoolean(void) = 0;
    virtual void writeBoolean (bool value) = 0;
    virtual double readDouble(void) = 0;
    virtual double readDoubleMin(void) = 0;
    virtual double readDoubleMax(void) = 0;
    virtual void writeDouble(double value) = 0;
    virtual int readEnumIndex(void) = 0;
    virtual void writeEnumIndex(int value) = 0;
    virtual std::string readEnumString(void) = 0;
    virtual void writeEnumString(std::string const & value) = 0;
    virtual void readEnumChoices(std::vector<std::string>& enumStrings, std::vector<int>& enumValues) = 0;
    virtual std::string readString(void) = 0;
    virtual void writeString(std::string const & value) = 0;
    virtual void writeCommand(void) = 0;
```
- GenICamFeatureSet
  - This provides mappings of all features both by asyn parameter index and by feature name.

- ADGenICam
  - This inherits from ADDriver and is the class from which real GenICam drivers inherit. 
  - It implements drvUserCreate(), writeInt32, writeFloat64(), etc. so that real drivers may not need these.
  - Inherited classes must implement the following pure virtual functions:
```
    virtual GenICamFeature *createFeature(GenICamFeatureSet *set,
                                          std::string const & asynName, asynParamType asynType,
                                          std::string const & featureName, GCFeatureType_t featureType) = 0;
    virtual asynStatus startCapture() = 0;
    virtual asynStatus stopCapture() = 0;
```

ADGenICam has a scripts directory containing Python scripts to create the Db file, adl file, and edl files.  These are very similar to those in aravisGigE but the drvInfo field in the .template file is different, etc.
```
-rwxrwxr-x 1 epics domain users 11676 Oct  7 10:01 makeAdl.py
-rwxrwxr-x 1 epics domain users 10138 Oct  8 16:46 makeDb.py
-rwxrwxr-x 1 epics domain users 13156 Oct  7 11:10 makeEdl.py
```

I have created a GenICam branch in ADSpinnaker which uses ADGeniCam.  It reduced size of ADSpinnaker.cpp by 40% from 1856 lines to 1161 lines.  The code for the GenICamFeature pure virtual functions is typically 2 lines each.  It also reduces the size of the template and startup file a lot.   The driver still needs work, but is basically functional.  I can control camera features and collect images.

I plan to work on ADVimba soon, which uses the new SDK for AVT/Prosilica cameras.

I am thinking to make a new ADAravis repository, rather than modifying aravisGigE.  That way aravisGigE can be maintained for backwards compatibility, and ADAravis is not constrained to be backwards compatible.

Thoughts?

**Comment by thomascobb** [comment]
This all sounds good, and I think making a new ADAravis repo is a good way to go. If you do this, I think Michael's reconnect branch is a better starting point than master, as the reconnect and polling behaviour is much better. However, I would still like to support two workflows:

1. IOC is master. In this case, the first connect would push the values in the database (either their initial values, or what autosave put there) into the camera. Any subsequent disconnect and reconnect of a camera would cause these settings to be re-pushed. This is what @mdavidsaver pull request currently implements.

2. Camera is master. In this case, the first connect would read values from the camera and push them to the database. Any reconnect would cause these settings to be re-read from the camera and re-pushed to the database. This is how aravisGigE master currently works, and is what DLS is used to. It makes debugging a camera much easier as setting some features have caused more flaky cameras to stop responding, and power cycling and then restoring these bad settings is not an option.

Would you be happy for a new ADAravis repo to support both workflows?

Investigating supporting both of these workflows on top of the @mdavidsaver pull request is the outstanding work that @LeeHudsonDLS still had to do, although I don't know how far he has got with it. If you get to ADAravis first, maybe this work becomes academic and we just leave aravisGigE with the pull request unmerged and fix in ADAravis?

**Comment by MarkRivers** [comment]
@thomascobb asked:
>Did you try giving aravis cap_net_raw?

I found that once I increased the Ethernet and USB buffer settings to those described in the [new ADGenICam documentation](https://areadetector.github.io/master/ADGenICam/ADGenICam.html#linux-usb-and-gige-system-settings) it worked fine without setting cp_net_raw.

Here is a screen shot of the Oryx 10 Gbit camera doing 162 frames/s, which is about 775 MB/s.  This is the full rated speed of this camera.
![image](https://user-images.githubusercontent.com/6115534/60184442-b454a400-97ed-11e9-98bf-4be6acf6e1db.png)

Here is a screen shot of the Grasshopper USB3 camera doing 152 frames/s, which is about 334 MB/s.  This is slightly less than rated speed of this camera (163 frames/s) but I usually find that the USB speeds are slightly less.

![image](https://user-images.githubusercontent.com/6115534/60185704-faab0280-97ef-11e9-8978-a9e8fb810e87.png)

These are running the master branch of ADGenICam and ADAravis.  I am pretty happy with them now.  The main issue is a bug in aravis itself.  Because it does not properly do register caching it takes a long time to read all of current feature settings, particularly on GigE cameras.  This introduces a long delay in startup as all of the PINI=YES records are processed, each of which results in reading back all of the new feature settings.  Hopefully this will be fixed in the near future.

**Comment by MarkRivers** [comment]
I just ran the Grasshopper3 USB3 camera with ADSpinnaker, rather than ADAravis.  With ADSpinnaker I can get the full frame rate of 163.5 frames/s.  This is on the same Ubuntu 18 computer as the tests above with no hardware changes.  Note that ADSpinnaker can only run on Ubuntu 18 and Windows, while ADAravis can run almost on any Linux OS.

![image](https://user-images.githubusercontent.com/6115534/60186679-e962f580-97f1-11e9-9ee9-29a7bab452e4.png)

**Comment by MarkRivers** [comment]
I am closing this issue, since this work is basically done.  I will open a new issue in ADGenICam concerning how to handle reconnects.
