### ISSUE TITLE
Update ADCore and ADFastCCD by accident. 

### ISSUE THREAD

**Issue by stuwilkins** [areaDetector/areaDetector#40]
Hi @MarkRivers, I think I screwed up adding the docs, by accident I have Updated ADCore and ADFastCCD to the latest master in the master branch. Is this an issue, I didn't realize that the module updates had been pulled in when I made the last commit. 

Apologies for this, it was not good, and I should have worked on a branch...... Sorry.

**Comment by MarkRivers** [comment]
Not sure exactly what you mean. I just merged you pull request in FastCCD.

**Comment by stuwilkins** [comment]
Sorry, I mean that I committed a change that updated the link from the ADCore and ADFastCCD so that the master branch of areaDetector now points to the master of ADCore and ADFastCCD that is all.

**Comment by MarkRivers** [comment]
Ok, no problem at all. Because we independently tag and release each submodule I have not worried too much about which submodule versions the top level points to.

**Comment by stuwilkins** [comment]
Ok thanks @MarkRivers, closing!
