### ISSUE TITLE
why build jpeg?

### ISSUE THREAD

**Issue by hanlet** [areaDetector/areaDetector#49]
Hi,
I'm attempting to build areaDetector on a 64bit SLF7.6 platform.  I believe that I'm correctly
following the INSTALL instructions.  In my CONFIG_SITE.local, I have 

# GraphicsMagick is required for NDFileMagick and the URL driver.
WITH_GRAPHICSMAGICK     = YES
GRAPHICSMAGICK_EXTERNAL = YES
# GraphicsMagick defines many global symbols, and one of these (SetImage) conflicts with a symbol
# in the Andor vendor library.  GraphickMagick provides a solution by allowing all external library
# symbols to be prefixed with "Gm".  Enable using this by default.  However, if a system library
# is used it may not be built with this option so this line should be commented out.
GRAPHICSMAGICK_PREFIX_SYMBOLS = YES
GRAPHICSMAGICK_INCLUDE = /usr/include/GraphicsMagick
GRAPHICSMAGICK_LIB     = /usr/lib64

# HDF5 is required for the NDFileHDF5 and NDFileNexus plugins
WITH_HDF5     = YES
HDF5_EXTERNAL = YES
#HDF5_INCLUDE =
#HDF5_LIB     =

# JPEG is required for the NDFileJPEG and NDFileTIFF plugins
WITH_JPEG     = YES
JPEG_EXTERNAL = YES
#JPEG_INCLUDE =
#JPEG_LIB     =

Likewise, in CONFIG_SITE.local.linux-x86_64, I have:
JPEG_EXTERNAL=YES
TIFF_EXTERNAL=YES

All that I have turned on in RELEASE_PRODUCTS.local is ADSupport.  What I don't understand
is that I cannot build areaDetector.  Why is the Makefile even going into supportApp/jpegSrc?

epics:~/epicsDEV/Support/areaDetector> make
make -C /home/epics/epicsDEV/Support/areaDetector/ADSupport install 
make[1]: Entering directory `/home/epics/epicsDEV/Support/areaDetector/ADSupport'
make -C ./configure install 
make[2]: Entering directory `/home/epics/epicsDEV/Support/areaDetector/ADSupport/configure'
perl /home/epics/epicsDEV/base/bin/linux-x86_64/makeMakefile.pl O.linux-x86_64 ../..
mkdir O.Common
make -C O.linux-x86_64 -f ../Makefile TOP=../.. \
    T_A=linux-x86_64 install
make[3]: Entering directory `/home/epics/epicsDEV/Support/areaDetector/ADSupport/configure/O.linux-x86_64'
perl /home/epics/epicsDEV/base/bin/linux-x86_64/convertRelease.pl checkRelease
make[3]: Leaving directory `/home/epics/epicsDEV/Support/areaDetector/ADSupport/configure/O.linux-x86_64'
make[2]: Leaving directory `/home/epics/epicsDEV/Support/areaDetector/ADSupport/configure'
make -C ./supportApp install 
make[2]: Entering directory `/home/epics/epicsDEV/Support/areaDetector/ADSupport/supportApp'
make -C ./jpegSrc install 
make[3]: Entering directory `/home/epics/epicsDEV/Support/areaDetector/ADSupport/supportApp/jpegSrc'
perl /home/epics/epicsDEV/base/bin/linux-x86_64/makeMakefile.pl O.linux-x86_64 ../../..
mkdir O.Common
make -C O.linux-x86_64 -f ../Makefile TOP=../../.. \
    T_A=linux-x86_64 install
make[4]: Entering directory `/home/epics/epicsDEV/Support/areaDetector/ADSupport/supportApp/jpegSrc/O.linux-x86_64'

/usr/bin/gcc -c  -D_GNU_SOURCE -D_DEFAULT_SOURCE            -D_X86_64_  -DUNIX  -Dlinux     -O3 -g   -Wall       -m64     -fPIC -MMD -I. -I../O.Common -I. -I../os/Linux -I../os/default -I.. -I../../../include/os/Linux -I../../../include    -I/home/epics/epicsDEV/Support/asyn/include       -I/home/epics/epicsDEV/base/include/os/Linux -I/home/epics/epicsDEV/base/include        ../decompressJPEG.c 
make[4]: *** No rule to make target `../../../lib/linux-x86_64/libjpeg.a', needed by `libdecompressJPEG.a'.  Stop.
make[4]: Leaving directory `/home/epics/epicsDEV/Support/areaDetector/ADSupport/supportApp/jpegSrc/O.linux-x86_64'
make[3]: *** [install.linux-x86_64] Error 2
make[3]: Leaving directory `/home/epics/epicsDEV/Support/areaDetector/ADSupport/supportApp/jpegSrc'
make[2]: *** [jpegSrc.install] Error 2
make[2]: Leaving directory `/home/epics/epicsDEV/Support/areaDetector/ADSupport/supportApp'
make[1]: *** [supportApp.install] Error 2
make[1]: Leaving directory `/home/epics/epicsDEV/Support/areaDetector/ADSupport'
make: *** [/home/epics/epicsDEV/Support/areaDetector/ADSupport.install] Error 2

**Comment by hanlet** [comment]
Sorry, I didn't use the html tags and the comments came out very large.

**Comment by MarkRivers** [comment]
You have found a problem in the Makefile in jpegSrc.  It needs to go into that directory because it builds not just libjpeg (which it won't build if JPEG_EXTERNAL=YES) but also libdecompressJPEG which is a little utility library for decompressing JPEG images used by ADViewers.  The latter is always built because it won't exist anywhere else. 

The Makefile was not properly building libdecompressJPEG when libjpeg is a system library.  The following patch should work:
```
corvette:ADSupport/supportApp/jpegSrc>git diff .
diff --git a/supportApp/jpegSrc/Makefile b/supportApp/jpegSrc/Makefile
index fa4dfb5..a9fa613 100644
--- a/supportApp/jpegSrc/Makefile
+++ b/supportApp/jpegSrc/Makefile
@@ -69,7 +69,16 @@ ifeq ($(WITH_JPEG),YES)

   LIBRARY  += decompressJPEG
   decompressJPEG_SRCS += decompressJPEG.c
-  decompressJPEG_LIBS += jpeg
+  ifeq ($(JPEG_EXTERNAL),NO)
+    decompressJPEG_LIBS += jpeg
+  else
+    ifdef JPEG_LIB
+      jpeg_DIR     = $(JPEG_LIB)
+      decompressJPEG_LIBS += jpeg
+    else
+      decompressJPEG_SYS_LIBS += jpeg
+    endif
+  endif
   decompressJPEG_SYS_LIBS_WIN32 += ws2_32

 endif # ($(WITH_JPEG),YES)
```

**Comment by MarkRivers** [comment]
I pushed the above patch to the master branch, so you can just try that.

**Comment by MarkRivers** [comment]
BTW, most people use ADSupport to build all support libraries, i.e. they set JPEG_EXTERNAL=NO, TIFF_EXTERNAL=NO, etc.  So using system libraries has not been tested as well we would like.  Please let me know if you run into other problems using system libraries.

**Comment by MarkRivers** [comment]
@hanlet have you had a chance to test my fix?

**Comment by MarkRivers** [comment]
Since @hanlet has not responded I am closing this.
