### ISSUE TITLE
Online docs for latest release, not just master

### ISSUE THREAD

**Issue by jlmuir** [areaDetector/areaDetector#58]
Is the [areaDetector documentation](https://areadetector.github.io/master/index.html) for the master branch?  If so, it would be very helpful to have another version for the latest release of areaDetector (e.g., 3-8).  Otherwise, someone who is, for example, attempting to install the latest release of areaDetector by following the Install Guide can end up running into problems because the Install Guide is for the master branch which might have diverged from the latest release.

This happens in real life.  I'm attempting to build areaDetector 3-8 by following the Install Guide, and it fails like this:

```
$ make
configure/RELEASE:5: configure/RELEASE_SUPPORT.local: No such file or directory
EPICS/Release.pm: Include file './configure/RELEASE_SUPPORT.local' not found
make: *** No rule to make target `configure/RELEASE_SUPPORT.local'.  Stop.
```

The Install Guide makes no mention of creating `configure/RELEASE_SUPPORT.local`.  I suspect this is because things have changed on the master branch, and the documentation reflects the master branch, not the release.

Looking in the `configure` directory, I see `EXAMPLE_RELEASE_SUPPORT.local`, so I can follow the pattern of copying that file to `RELEASE_SUPPORT.local`, and it works.  But it would be nice to not have to run into problems like this.  And depending on the change in master compared to the latest release, the fix might not be so simple next time.

**Comment by MarkRivers** [comment]
It is true that the version of the documentation on github.io is for the master branch.

However, the documentation for each release is included in that release.

In your case:
https://github.com/areaDetector/areaDetector/blob/R3-8/docs/source/install_guide.rst

which does document RELEASE_SUPPORT.local.

If you would like to submit a pull request to have areadetector.github.io have the documentation for each release I will be happy to consider it.  Keep in mind that it is a single document, and there are independent releases of each detector module (ADProsilica, ADPilatus, etc.), so this could get pretty complex.

**Comment by jlmuir** [comment]
I know `install_guide.rst` is included in the release, but something rendered as HTML (or a similarly rich format) is nicer to read.

Having just two versions would be enough for me: the latest release and master.

I would say for the latest release, it should just be the latest release of areaDetector and the latest release of each of the drivers and plugins.  And if a driver or plugin gets a new release, then that new release is what gets included even if areaDetector has not had a new release.  The idea is just to provide documentation for this approach of installing areaDetector by grabbing the latest release and the latest release of all the desired drivers and plugins.

I'm just looking at it from the standpoint of a person trying to download and build areaDetector from source, and if the idea is that people should be able to do that by either downloading tarballs for the latest releases or by checking out the master branches of all the repos, then it seems like it would be good to provide documentation online for them to be able to do that for the latest-release-tarballs approach.

I don't know how it's all being generated, so I don't know how easy or hard it would be.  If it's easy, then I could have a look.  If it's hard, though, then I guess this issue should be closed because you know more about how it's being generated than me, and I wouldn't want to spend a lot of time on it.

**Comment by MarkRivers** [comment]
> I know install_guide.rst is included in the release, but something rendered as HTML (or a similarly rich format) is nicer to read.

This link **_is_** rendered in HTML and is fine to read.

https://github.com/areaDetector/areaDetector/blob/R3-8/docs/source/install_guide.rst

> I don't know how it's all being generated, so I don't know how easy or hard it would be. If it's easy, then I could have a look. 

It's built with Sphinx from the Makefile in this directory:
https://github.com/areaDetector/areaDetector/tree/master/docs

and files in this directory:
https://github.com/areaDetector/areaDetector/tree/master/docs/source

and this Travis script:
https://github.com/areaDetector/areaDetector/blob/master/.travis.yml

**Comment by jlmuir** [comment]
I didn't know GitHub could render reStructuredText!  Thanks for that!  That's what I'll use.

I still think that if the method of installing areaDetector using the latest release tarballs is considered a first-class citizen, it would make sense to list both versions of the documentation at the root of the documentation so that a user can choose the version of the documentation appropriate for what they're doing.  But anyway, if you don't think so, or if it's too much work, then this issue can be closed.
