### ISSUE TITLE
Last Update

### ISSUE THREAD

**Issue by Ricardo-Herrero** [areaDetector/areaDetector#8]
Hello,

 I´m trying to install new release of area Detector, but I need one more product that is not included in the Install guide, the devIocStats product. I have tried to install it under directory /support/, but still areaDetector can´t find it. Finally I copied it into the directories where it is trying to find it, ADCore/iocs/simDetectorIOC/lib/linux-x86_64/libdevIocStats.a and ADCore/iocs/simDetectorNoIOC/lib/linux-x86_64/libdevIocStats.a 
However I have found another compilation problem, /opt/epics/base-3.14.12.4/support/areaDetector/ADCore/iocs/simDetectorIOC/simDetectorApp/src/O.linux-x86_64/simDetectorApp_registerRecordDeviceDriver.cpp:630: reference to`pvar_func_editSseqRegistrar' is not defined.

I will try to download a previous version of areaDetector, when will the new version be available? Thanks in advance for your help.

Regards, Ricardo Herrero

**Comment by MarkRivers** [comment]
Hi Ricardo,

I think you have pulled the master branch of ADCore.  When you do that you should also pull the master branch of the top-level areaDetector directory.  You will see that areaDetector/configure/EXAMPLE_RELEASE_PRODS.local has been changed to include DEVIOCSTATS.  You should add those lines to your areaDetector/configure/RELEASE_PRODS.local.  That is all you need to do.

You are correct that I forgot to update areaDetector/INSTALL_GUIDE.md to include DEVIOCSTATS.  I have now done that and pushed to github.

Let me know if you still have problems.

Mark

________________________________

**Comment by MarkRivers** [comment]
Issue fixed.
