### ISSUE TITLE
Copying an areadetector image from another IOC

### ISSUE THREAD

**Issue by bsobhani** [areaDetector/areaDetector#81]
Is there an IOC that can copy the ArrayData PV from another IOC over channel access (e.g. for further processing)? I have been looking at NDDriverStdArrays, but it does not seem to be what I want, because the INP field of its ArrayIn PV seems to be set to something internal `("@asyn($(PORT),$(ADDR),$(TIMEOUT))NDSA_ARRAY_DATA"`), whereas I would like to read the input array externally, over channel access, from a PV running on a different IOC.

I want to make an IOC that copies an image over channel access, and then assigns it to a port, so that I can apply plugins in order to transform it.

**Comment by MarkRivers** [comment]
The reason for using pvAccess rather than Channel Access is that pvAccess can transmit the entire NDArray correctly, including dimensions, data type, and metadata.  Channel Access has to flatten the array to 1-D and is fixed to the data type of the waveform record being used.

**Comment by bsobhani** [comment]
This looks like it would work (I see the pvaDriver even has a PvName field), but I would prefer not to modify the original IOC yet. The NDDriverStdArrays looks frustratingly close to what I want so I am continuing to look into this. But since the INP field for the ArrayIn PV is "taken", it looks like the only way to get data to it is with caput, and not through any kind of database record processing (I tried using the seq record but it did not work). Is this the case?

**Comment by bsobhani** [comment]
Thank you. I believe this is what I want.
