### ISSUE TITLE
 a new driver for Basler cameras using Pylon SDK

### ISSUE THREAD

**Issue by xiaoqiangwang** [areaDetector/areaDetector#83]
I currently use ADAravis driver to control some Basler GigE and USB3 cameras. However the Aravis library does not support other high speed interfaces like CoaXPress and CameraLink. 

As an exercise to get familiar with GenICam driver principles, I made an ADGenICam derived driver using their Pylon SDK. It was modified from ADVimba driver but also took references from ADSpinnacker driver.  I have tested the driver with the emulation camera and a USB3 camera, on both Debian testing and Windows systems.

The driver is at https://github.com/xiaoqiangwang/ADPylon. If it is considered useful, I would be happy to transfer it under the areaDetector org.

**Comment by MarkRivers** [comment]
That sounds great, I'll be happy to add it to the areaDetector organization.

**Comment by xiaoqiangwang** [comment]
Thanks for being positive. To proceed with the transfer, would you invite me to the areaDetector org?

**Comment by MarkRivers** [comment]
I have sent you an invitation.

**Comment by xiaoqiangwang** [comment]
Strange that I have not received notifications yet. My username is **xiaoqiangwang** in case there are other like named.

**Comment by MarkRivers** [comment]
I sent the invitation to your @psi e-mail address

**Comment by MarkRivers** [comment]
I looked and there is no pending invitation, so something must have gone wrong.  I have sent it again to your Github username.

**Comment by xiaoqiangwang** [comment]
I have made the transfer https://github.com/areaDetector/ADPylon, thanks!

The mail invitation could be caught by the spam filter.
