### ISSUE TITLE
add c++11 to Darwin build

### ISSUE THREAD

**Issue by hjunkes** [areaDetector/areaDetector#87]
To be able to build areadetector on Darwin I made a small addition.

diff --git a/ADApp/pluginSrc/Makefile b/ADApp/pluginSrc/Makefile
index 471356d6..f3e2c74f 100644
--- a/ADApp/pluginSrc/Makefile
+++ b/ADApp/pluginSrc/Makefile
@@ -12,6 +12,7 @@ USR_CXXFLAGS_Linux += -DH5_NO_DEPRECATED_SYMBOLS -DH5Gopen_vers=2

 # json.hpp requires C++11
 NDPluginBadPixel_CXXFLAGS_Linux += -std=c++11
+NDPluginBadPixel_CXXFLAGS_Darwin += -std=c++11

 ifneq ($(SHARED_LIBRARIES), YES)
    USR_CFLAGS_WIN32 += -DLIBXML_STATIC

**Comment by MarkRivers** [comment]
I fixed this and pushed to Github.
