### ISSUE TITLE
Type in configure/EXAMPLE_RELEASE.local

### ISSUE THREAD

**Issue by hjunkes** [areaDetector/areaDetector#88]
There is a type in EXAMPLE_RELEASE.local

#ADCSIMDETECTOR=$(AREA_DETECTOR)/ADCSimDetector

Should be? ("C" is too much)
#ADSIMDETECTOR=$(AREA_DETECTOR)/ADSimDetector

**Comment by MarkRivers** [comment]
No, that line is correct.  There are 2 separate drivers:
ADSimDetector: 
https://github.com/areaDetector/adsimdetector
https://areadetector.github.io/areaDetector/ADSimDetector/simDetector.html

ADCSimDetector: 
https://github.com/areaDetector/adcsimdetector
https://areadetector.github.io/areaDetector/ADCSimDetector/ADCSimDetectorDoc.html
